language: cpp

os:
  - linux
  - osx

branches:
  only:
    - develop
    - master
    - testing

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken> --add env.global`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    # and: https://docs.travis-ci.com/user/best-practices-security/
    - secure: SU8ZNOzs3sRC/tzLF2yvGKJOyiGb/RvEcTDupwXcrOLyhcc0HvmSSYPvsgVllTyUlycH7maTbztUei+W4zqqtbKCxhVEuShEi6k5qWS/1QgfJ8f/rT2IpdVftmOGFHB9J454HwFQJhoRtEuJ0dCSsOp7S5iAC/RrRqyfh+KSoPY=
  matrix:
    - CONFIG=release
    #- CONFIG=debug

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      lsb_release -a
      sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-add-repository -y ppa:beineri/opt-qt562
      sudo apt-get -qq update
      sudo apt-get -qq install g++-4.8 libc6-i386 qt56tools qt56svg qt56webkit qt56script
      export CXX="g++-4.8"
      export CC="gcc-4.8"
    fi
  # OS X Qt http://braumeister.org/search/qt5
  # we need to use macdeployqtfix after using macdeployqt to fix the library paths!
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      brew update > /dev/null
      brew install qt5
      export QTDIR="/usr/local/opt/qt5"
    fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      QTDIR="/opt/qt56"
      PATH="$QTDIR/bin:$PATH"
      qt56-env.sh
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
      PATH="$QTDIR/bin:$PATH"
      LDFLAGS=-L$QTDIR/lib
      CPPFLAGS=-I$QTDIR/include
    fi
  - cd src
  - qmake LogAnalyzer.pro CONFIG+=$CONFIG
  - make

before_deploy:
  - export VERSION_NUMBER=`cat version.h | sed "s/[^0-9,.]//g"`
  # create a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         ../build-systems/travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - TIME_STRING=`date +%H%M%S`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    fi
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/pbek/loganalyzer --tags >/dev/null 2>&1

deploy:
  - provider: releases
    api_key:
        secure: TpCVgaGIR+65wUKWGglg5F9HUXrOOXTMJEgmc4w4hjSnzTg1IuZWGE5EC7Q87vigLrpkRGObIS6xygY8Qxm1eCjY4GmyBWr+R22yBwcsf850cWAYhPQ4RLWeRTr7xErvdu/NOiC8uFa7eRjaT3WJGndDY8UjsndTbjb4ADySc7h1UN8xleJKGhdvQSC11aHqileuGgspGKLu+GVgzshGId/uE3dJGaDKOU+pV2oTBOcvihEgGlrtQsxkljs207Oaicg+5BFDGshGdq22cMQDy85BlX00blUzt8TDbK6TEDmlg6xUIBLxn1gn2JnbUC0zoFM5SUdR3mMhvEoUrz0QRSdRwjQTTuL6y6x3mIVnUngs8/IAEhbzdrf5xbYv4kG3NdR7kTu7ej6zaGrAfQwycwwUmzWRkiJiMcAZOYLAtBbanGQ0o+YAeHUykDGVsOnWFCYQLmxZo1KyGHNuDUmA9eAum9cw7PRWS5glrItUelwS9cLcZMzQ27QhUBPKTXcAu/l1sfbrUgxwxYxEAxYrjtaNieeoHJLItJycX7oPof2Sl7pVyejHXIMviyeA/FdwuNJKzsEwIjAJU24c6NszoPZ+0oD7cFBjE3vycA/nBwRRlJ4uJ6L5ovK4ZFAEdBt6nHHjq0Q7x8t3PROx8eWJIMeG+560TqdSGmePuwNmq50=
    file: LogAnalyzer-$VERSION_NUMBER.dmg
    skip_cleanup: true
    on:
        repo: pbek/loganalyzer
        branch: master
#        branch: develop
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = osx

notifications:
  recipients:
    - developer@bekerle.com
  email:
    on_success: change
    on_failure: change
  irc:
    # https://docs.travis-ci.com/user/notifications/#IRC-notification
    channels:
      - "chat.freenode.net#fuf"
    template:
      - "[%{commit}] %{repository} (%{branch}): %{message}"
      - "[%{commit}] Commit message : %{commit_message}"
      - "[%{commit}] Change view : %{compare_url}"
      - "[%{commit}] Build details : %{build_url}"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
