language: cpp

os:
  - linux
  - osx

branches:
  only:
    - develop
    - master
    - testing

env:
  global:
    # $TAGPERM environment variable
    # generate a token at https://github.com/settings/tokens and encrypt it
    # with `travis encrypt TAGPERM=<yoursecrettoken> --add env.global`
    # also see: https://docs.travis-ci.com/user/encryption-keys/#Usage
    - secure: tw2iN29O8KOzTTt/5aXcniGmHD/2N5I6RFdkDSeWvpI7DEYfPuVwUfuOosaU5Fc7Pf+qMCyzZtHyjKIrmVQ/DsD0hRF+0GvnN3a70x7B7+CfzU73w0TYAleYw542N7bGssOxHnNZa5nAIwT+h9yK1jf1JQ5uy526xpcP19v9Wz4jXbQfP+KM9luefpqZF8lSUF5ElRvbH5YIJF8Kvqie349YXbsmRQcI9bFuJMzNsucinKNPpLGUCDM3AkPRCrRFJQ5Z7qj0U6HuotIFiMLD8Wy2ZBfzA3cO/YXgl4O9gFFaFZXEhEGqRKvpccdyzh00mbyciH+S7ybcobLPqdfwO5s46hxk5VtNHygHvwTaMq+TQ5jAnOcCC7Bj7qT1RZAtwQbKHAEpavej3kdcIj7oneQJJZSkr4MVLBcvi+6sawxQ74jQvmPbRExeO6kqHnc1TUo4HXcIYmv+TLYeliXvlP11MXysQ6k0JumvvpAeuV3ZYLdmi1bPcs2OfTIi8eN7Vr/Ua+SlEe93od7i3lwVo9/3EEZG/X9Z9QXWoc5riYoWFnxO3/uMkoqX+IlTLllItminfUfwB+XXNZx4EJk0ek6nxt0PWfmtfnrrl0TzchTdiqmT0ciKO7Zr1+BPiLl2W1HB5a8vXtJNprodpHMUehlBGvRpMIlsqVAK3qfqRME=
  matrix:
    - CONFIG=release
    #- CONFIG=debug

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update > /dev/null
      && brew install qt5
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
    else
         QTDIR="/usr/local/opt/qt5"
      && PATH="$QTDIR/bin:$PATH"
      && LDFLAGS=-L$QTDIR/lib
      && CPPFLAGS=-I$QTDIR/include
      ;
    fi
  - cd src
  - qmake LogAnalyzer.pro CONFIG+=$CONFIG
  - make

before_deploy:
  - export VERSION_NUMBER=`cat version.h | sed "s/[^0-9,.]//g"`
  # create a disk image for OSX
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         ../build-systems/travis/create-dmg.sh
      ;
    fi
  #
  # add a tag
  #
  - TIME_STRING=`date +%H%M%S`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         export GIT_TAG=macosx-b$TRAVIS_BUILD_NUMBER-$TIME_STRING
      ;
    fi
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/pbek/loganalyzer --tags

deploy:
  - provider: releases
    api_key:
        secure: "Q/G+YH4A3gfYBmdwPcqCbf5xAiKC5sceanaPF1qz/bj0BJ/HX9QTYonVkePjIqj8VVjVTprkOj6AqTupuuthhupVHBIZPLxB0GT75COCDziDg2vZuancyveCixPioziHzT+28UJOuvwSIjJmfwpxArukWG+Z1eyZ6ZA30/k0lo9u5vbceNYUq6iQti4/2bszJrs9e8lbm227hYMG/txdTsTUe6TQlA7+owFULbVlgBz5gqYqgbOyY5bQ6xB7IZx6hLSqnstdqSw+fzu23nD6XceWfqbuEJDpXqaMZt+xaNTh21hkUoAOa5Kzjltl/I4bpftvUvmkoEIhrriSWOj4sE/9jtjDf3jjeAoBpMXzF3/LkPx5THwnn1z2Oc9ugumpMluumxi3KKVQV06rBFaHUxVr6KGenBRWn2WCYq5E4ha4khUtOO9gzcxQNRZcXGFEcMrDNZQW7BdtzfWzSOYgMSd8IPtrbVzBy8tVaauSrcn7wcZ6WYTAvRE4TT6aiEJ+XChxXvdjp/EJ+DwoKFujFW68onLTQKMXnrnDQ+Qa9d+6bTjFgNa0wT3anLy53mrnqWCNkeU8oTDZCJqD2Jj2QGOWcoABnuGWeQG/023p0fDNK29GwjPOFi44+N/RcARNajzuurnQsACBdNPMuDSxCazaPNA/sMn5SwVouNN0rK8="
    file: LogAnalyzer-$VERSION_NUMBER.dmg
    skip_cleanup: true
    on:
        repo: pbek/loganalyzer
        branch: master
#        branch: develop
        tags: false
        condition: $CONFIG = release && ${TRAVIS_OS_NAME} = osx

notifications:
  recipients:
    - developer@bekerle.com
  email:
    on_success: change
    on_failure: change
  irc:
    # https://docs.travis-ci.com/user/notifications/#IRC-notification
    channels:
      - "chat.freenode.net#fuf"
    template:
      - "[%{commit}] %{repository} (%{branch}): %{message}"
      - "[%{commit}] Commit message : %{commit_message}"
      - "[%{commit}] Change view : %{compare_url}"
      - "[%{commit}] Build details : %{build_url}"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
