# AppVeyor build configuration
# http://www.appveyor.com/docs/build-configuration
os: unstable
skip_tags: true

install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  - set RELEASE_PATH=build-systems\appveyor\release

build_script:
  - cd src
  # we need to modify that to make it running on AppVeyor
  - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" LogAnalyzer.pro
  - "echo #define RELEASE \"AppVeyor\" > release.h"
  - qmake LogAnalyzer.pro -r -spec win32-g++
  - mingw32-make
  # creating the release path
  - md ..\%RELEASE_PATH%
  # copy the binary to our release path
  - copy release\LogAnalyzer.exe ..\%RELEASE_PATH%
  - cd ..\%RELEASE_PATH%
  # fetching dependencies of QT app
  # http://doc.qt.io/qt-5/windows-deployment.html
  - windeployqt --release LogAnalyzer.exe
  # this dll was missed by windeployqt
  - copy ..\libwinpthread-1.dll . /y
  # this dll didn't work when released by windeployqt
  - copy "..\libstdc++-6.dll" . /y

artifacts:
  # pushing entire folder as a zip archive
  - path: build-systems\appveyor\release
    name: LogAnalyzer

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: LogAnalyzer
    draft: false
    prerelease: false
    auth_token:
      secure: spcyN/Dz3B2GXBPii8IywDLq6vfxC1SrN+xR2wMerFM7g2nTy0Lrh5agQONFoInR
    on:
      branch: master
