name: loganalyzer-pbek
version: git
version-script: cat src/version.h | sed "s/[^0-9,.]//g"
summary: Helps you analyzing log files by reducing the content with regular expressions
grade: stable
confinement: strict
base: core18
description: |
  LogAnalyzer is a tool that helps you analyzing your log files by reducing
  the content with regular expression patterns you define.
  https://github.com/pbek/LogAnalyzer

apps:
  loganalyzer-pbek:
    command: desktop-launch ${SNAP}/usr/bin/LogAnalyzer -style=Fusion --snap
    environment:
      DISABLE_WAYLAND: 1
    # see https://docs.snapcraft.io/reference/interfaces
    plugs:
      - x11
      - unity7
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - removable-media
      - opengl
      - cups-control

parts:
  loganalyzer-pbek:
    source: .
#    source: https://github.com/pbek/loganalyzer.git
    # see https://docs.snapcraft.io/reference/plugins/qmake
    plugin: qmake
    qt-version: qt5
#    source-branch: develop
    options:
      - ./src
      - CONFIG+=release
    build-packages:
      - qttools5-dev
      - build-essential
      - libqt5svg5-dev
      - qttools5-dev-tools
    stage-packages:
      - libqt5gui5
      - libqt5sql5
      - libqt5sql5-sqlite
      - libqt5widgets5
      - libqt5svg5
      - libqt5network5
      - libqt5printsupport5
      - qtwayland5
    stage:
      - -usr/share/pkgconfig
    after: [desktop-qt5]

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
