name: loganalyzer
version: "VERSION-STRING"
summary: Helps you analyzing log files by reducing the content with regular expressions
grade: stable
confinement: strict
description: |
  LogAnalyzer is a tool that helps you analyzing your log files by reducing
  the content with regular expression patterns you define.
  https://github.com/pbek/LogAnalyzer

apps:
  loganalyzer:
    command: desktop-launch ${SNAP}/usr/bin/LogAnalyzer -style=Fusion --snap
    environment:
        DISABLE_WAYLAND: 1
    # see https://docs.snapcraft.io/reference/interfaces
    plugs:
      - x11
      - unity7
      - network
      - network-bind
      - home
      - desktop
      - desktop-legacy
      - removable-media
      - opengl
      - cups-control

parts:
  loganalyzer:
    source: https://github.com/pbek/loganalyzer.git
    # see https://docs.snapcraft.io/reference/plugins/qmake
    plugin: qmake
    qt-version: qt5
    source-branch: develop
    options:
    - ./src
    - CONFIG+=release
    build-packages:
      - qttools5-dev
      - build-essential
      - libqt5svg5-dev
      - qttools5-dev-tools
    stage-packages:
      - libqt5gui5
      - libqt5widgets5
      - libqt5svg5
      - qtwayland5
    stage:
      - -usr/share/pkgconfig
    after: [desktop-qt5]
