name: Build LogAnalizer
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          aqtversion: '==3.1.*'
          version: '5.10.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win32_mingw53'
          cache: true
      - name: Checkout
        uses: actions/checkout@v3
      - id: MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: x86
          version: 12.2.0
      - name: cmds
        run: |
          cd src
          sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" LogAnalyzer.pro
          echo "#define RELEASE \\"GHA\\"" > release.h
          qmake LogAnalyzer.pro -r -spec win32-g++
          mingw32-make
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: LogAnalyzer
          path: src\release\LogAnalyzer.exe
            
